name: flow_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  sqflite_common: ^2.5.4
  crypto: ^3.0.2
  collection: ^1.17.2
  web_socket_channel: ^3.0.1
  dart_mappable: ^4.3.0
  dart_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      ref: b7787191b0705ff0a22149409b1b360468d9e06d
      path: packages/dart_leap
dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  lints: ^5.0.0
  test: ^1.25.4
